qcc/basic_app/urls.py
from django.conf.urls import url
from django.urls import path
from basic_app import views

app_name = 'basic_app'

urlpatterns = [
    url(r'^$',views.IndexView.as_view(),name='index'),
    url(r'^register/$',views.RegisterView.as_view(),name='register'),
    #url(r'^other/$',views.other,name='other'),
    url(r'^user_login/$',views.LoginView.as_view(),name='user_login'),
    url(r'^home/$',views.HomeView.as_view(),name='home'),
    #url(r'^home/(?P<pk>\d+)/$', views.SubjectView.as_view(), name='subject_detail'),
    path('home/<int:pk>/', views.SubjectView.as_view(), name='subject_detail'),
    path('home/<int:sid>/<int:tid>', views.FrameView.as_view(), name='frame'),
    path('home/<int:sid>/<int:tid>/test', views.TestView.as_view(), name='test'),
    path('home/<int:sid>/<int:tid>/test/<int:testSaved>', views.TestView.as_view(), name='test'),
]

qcc/qcc/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.urls import path
from basic_app import views

urlpatterns = [
    url(r'^$',views.IndexView.as_view(),name='index'),
    path('admin/', admin.site.urls),
    url(r'^basic_app/',include('basic_app.urls')),
    url(r'^logout/$',views.LogoutView.as_view(),name="logout")
]

qcc/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, models.CASCADE)

    admission_number = models.CharField(max_length=10)
    address = models.CharField(max_length=256)
    contact = models.CharField(max_length=10)    

    def __str__(self):
        return self.user.username

class Subject(models.Model):
    subject_name = models.CharField(max_length=25)
    img_url = models.CharField(max_length=256,null=True)

    def __str__(self):
        return self.subject_name

class Topic(models.Model):
    topic_name = models.CharField(max_length=255)
    img_url = models.CharField(max_length=256,null=True)
    subject = models.ForeignKey(Subject,on_delete=models.CASCADE)

    def __str__(self):
        return self.topic_name 

class Video(models.Model):
    video_name = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    url = models.CharField(max_length=255)
    topic = models.ForeignKey(Topic,on_delete=models.CASCADE)

    def __str__(self):
        return self.video_name                

class Frame(models.Model):
    frame_name = models.CharField(max_length=255)
    frame_description = models.TextField(null=True)
    img_url = models.CharField(max_length=256,null=True)
    topic = models.ForeignKey(Topic,on_delete=models.CASCADE)

    def __str__(self):
        return self.frame_name                

class Question(models.Model):
    question = models.CharField(max_length=255)
    frame = models.ForeignKey(Frame,on_delete=models.CASCADE)

    def __str__(self):
        return self.question

class Option(models.Model):
    option = models.CharField(max_length=255)
    answer = models.BooleanField(default=False)
    question = models.ForeignKey(Question,on_delete=models.CASCADE)

    def __str__(self):
        return self.option

class Test(models.Model):
    name = models.CharField(max_length=255)
    max_questions = models.IntegerField()
    subject = models.ForeignKey(Subject,on_delete=models.CASCADE)
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE, null=True, blank=True)
    frame = models.ForeignKey(Frame, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.name

class TestResult(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    test = models.ForeignKey(Test, on_delete=models.CASCADE)
    question = models.ForeignKey(Question,on_delete=models.CASCADE)
    user_answer = models.ForeignKey(Option,on_delete=models.CASCADE)

qcc/basic_app/forms.py
from django import  forms
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfo

class UserForm(forms.ModelForm):
    #password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('admission_number','address','contact')

qcc/basic_app/views.py
from django.shortcuts import render,redirect,get_object_or_404
from basic_app.forms import UserForm, UserProfileInfoForm

from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect,HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.views.generic import View, TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from . import models
from django.utils.decorators import method_decorator
from django.contrib.auth.models import User
import random

# Create your views here.
class IndexView(View):
    def get(self,request):
        #context_dict = {'text':'hello world', 'num':55}
        if request.user.is_active:
            return redirect('/basic_app/home/',{'username':request.user.username})
        return render(request,'basic_app/index.html')

class HomeView(View):
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get(self,request):
        #context_dict = {'text':'hello world', 'num':55}
        #user = request.session.get('user')
        subject_list = models.Subject.objects.all()
        return render(request,'basic_app/home.html',{'subject_list':subject_list})

class LoginView(View):
    def post(self,request):
        username = request.POST.get("username")
        password = request.POST.get("password")

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                #return HttpResponseRedirect(reverse('index'))
                return redirect('/basic_app/home/',{'username':username})
            else:
                return render(request,'basic_app/login.html',{'loginError':"User Not Active !"})
                #return HttpResponse("User Not Active !")
        else:
            return render(request,'basic_app/login.html',{'loginError':"Invalid Login !"})
            #return HttpResponse("Invalid Login !")
    def get(self,request):
           
        if request.user.is_authenticated:
            return redirect('/basic_app/home/',{'username':request.user.username})
        else:
            return render(request,'basic_app/login.html',{})


class LogoutView(View):
    
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get(self,request):
        logout(request)
        return HttpResponseRedirect(reverse('index'))

class RegisterView(View):
    def post(self,request):
        registered = False
        user_form = UserForm(data = request.POST)
        profile_form = UserProfileInfoForm(data = request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user            
            profile.save()
            registered = True
        else:
            print(user_form.errors,profile_form.errors)
        return render(request,'basic_app/registration.html',{'user_form':user_form,'profile_form':profile_form,'registered':registered})
    def get(self,request):        
        if request.user.is_authenticated:
            return redirect('/basic_app/home/',{'username':request.user.username})
        else:
            user_form = UserForm()
            profile_form = UserProfileInfoForm()
            return render(request,'basic_app/registration.html',{'user_form':user_form,'profile_form':profile_form,'registered':False})

class SubjectView(View):
    
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get(self,request, pk):
        
        subject = models.Subject.objects.filter(id=pk)
        topics_list = models.Topic.objects.filter(subject=pk)

        data = {
            'topics_list':topics_list,
            'subject' : subject
        }
        return render(request,'basic_app/subject.html',data)

class FrameView(View):
    
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get(self,request, sid, tid):
        
        frames_list = models.Frame.objects.filter(topic=tid)
        topic = models.Topic.objects.filter(id=tid)
        subject = models.Subject.objects.filter(id=sid)
        test = models.Test.objects.filter(topic=tid).exists()
        if test:
            user_test = models.TestResult.objects.filter(test=models.Test.objects.get(topic=tid)).filter(user=request.user.id).exists()
        else:
            user_test = False
        
        data = {
            'frames_list' : frames_list,
            'topic' : topic,
            'subject' : subject,
            'test' : test,
            'user_test' : user_test,
            'user' : request.user
        }
        return render(request,'basic_app/frames.html',data)

class TestView(View):
    
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get(self,request, sid, tid, testSaved=0):
        data = dict()
        topic = models.Topic.objects.filter(id=tid)
        subject = models.Subject.objects.filter(id=sid)
        frames = models.Frame.objects.filter(topic=tid)        
        test = models.Test.objects.filter(topic=tid)
        data['topic'] = topic
        data['subject'] = subject
        data['test'] = test
        data['testSaved'] = testSaved
        max_qns = 0
        for t in test: 
            max_qns = t.max_questions
                
        if test:                                
            data['test_taken'] = models.TestResult.objects.filter(test=models.Test.objects.get(topic=tid)).filter(user=request.user.id).exists()
            
            if data['test_taken']:
                question_list = models.Question.objects.filter(frame__in=frames.all())
            else:
                valid_question_id_list = models.Question.objects.filter(frame__in=frames.all()).values_list('id', flat=True)
                random_question_id_list = random.sample(list(valid_question_id_list), min(len(valid_question_id_list),max_qns))
                question_list = models.Question.objects.filter(id__in=random_question_id_list)                
            data['question_list'] = question_list

            option_list = models.Option.objects.filter(question__in=question_list.all())
            data['option_list'] = option_list           
            answer_paper = models.TestResult.objects.filter(test=models.Test.objects.get(topic=tid)).filter(user=request.user.id)
            
            data['answer_paper'] = answer_paper
        else:
            data["test_not_found"] = True

        return render(request,'basic_app/test.html',data)

    def post(self,request, sid, tid):
        if request.POST.get("numberOfQns"):
            for x in range(1,int(request.POST.get("numberOfQns"))+1):
                testAnswers = models.TestResult()
                testAnswers.user = get_object_or_404(User, id=request.user.id)
                testAnswers.test = get_object_or_404(models.Test, id=request.POST.get("testId"))
                testAnswers.question = get_object_or_404(models.Question, id=request.POST.get("qn"+str(x)))
                testAnswers.user_answer = get_object_or_404(models.Option, id=request.POST.get("qn"+str(x)+"Ans"))
                testAnswers.save()
            #return HttpResponse("Success")
            return redirect('basic_app:test',sid=sid,tid=tid, testSaved='1')

qcc/templates/basic_app/base-orig.html
<!DOCTYPE html>
<html lang="en">


<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MGM</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <style>
        /* body {
            background: url("/static/basic_app/ol3.jpeg");
            background-size: 50%;
            background-attachment: fixed;
            background-position: center;
            background-repeat: no-repeat;
        } */
    </style>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark shadow-sm" style="background-color: #00578a;">
        {% if user.is_authenticated %}
        <a class="navbar-brand" href="{% url 'basic_app:home' %}" style="text-shadow: 2px 2px 5px  #000c0c ; font-family: 'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif;">MGM</a> {% else %}
        <a class="navbar-brand" href="{% url 'index' %}" style="text-shadow: 2px 2px 5px  #000c0c ; font-family: 'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif;">MGM</a> {% endif %}

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            {% if user.is_authenticated %}
            <ul class="navbar-nav ml-auto">
                <li class="nav-item dropdown" style="float: right;">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        {{ user.username }}
                      </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'basic_app:home' %}">Dashboard</a>
                        <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                    </div>
                </li>
            </ul>
            {% else %}
            <ul class="navbar-nav">
                <!-- <li class="nav-item">
                    <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
                </li> -->

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'basic_app:register' %}">Register</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'basic_app:user_login' %}">Login</a>
                </li>
            </ul>
            {% endif%}
        </div>
    </nav>

    <div class="container">
        {% block body_block %} {% endblock %}
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</body>

</html>

qcc/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en">


<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MGM</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <style>
        /* body {
            background: url("/static/basic_app/ol3.jpeg");
            background-size: 50%;
            background-attachment: fixed;
            background-position: center;
            background-repeat: no-repeat;
        } */
        /* body {
            background-image: linear-gradient(-90deg, #521EBA, #1C57E9);
        } */
        
        @font-face {
            font-family: 'fo';
            src: local('FO'),
            url("{% static 'basic_app/fonts/fo.ttf' %}") format("truetype");
        }
        
        @font-face {
            font-family: 'acme';
            src: local('ACME'),
            url("{% static 'basic_app/fonts/Acme-Regular.ttf' %}") format("truetype");
        }
        
        @font-face {
            font-family: 'anton';
            src: local('ANTON'),
            url("{% static 'basic_app/fonts/Anton-Regular.ttf' %}") format("truetype");
        }
        
        @font-face {
            font-family: 'lobster';
            src: local('LOBSTER'),
            url("{% static 'basic_app/fonts/Lobster-Regular.ttf' %}") format("truetype");
        }
        
        @font-face {
            font-family: 'roboto';
            src: local('ROBOTO'),
            url("{% static 'basic_app/fonts/Roboto-Regular.ttf' %}") format("truetype");
        }
    </style>
</head>

<body {% if user.is_authenticated %} {% else %} style="background-image: linear-gradient(-90deg, #521EBA, #1C57E9)" {% endif %}>
    <nav class="navbar {% if user.is_authenticated %} {% else %}fixed-top {% endif %} navbar-expand-lg navbar-dark {% if user.is_authenticated %} {% else %}container{% endif %}" style="background-image: linear-gradient(-90deg, #521EBA, #1C57E9);">
        {% if user.is_authenticated %}
        <a class="navbar-brand" href="{% url 'basic_app:home' %}" style="font-family: fo;">MGM</a> {% else %}
        <a class="navbar-brand" href="{% url 'index' %}" style="font-family: fo;">MGM</a> {% endif %}

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            {% if user.is_authenticated %}
            <ul class="navbar-nav ml-auto">
                <li class="nav-item dropdown" style="float: right;">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        {{ user.username }}
                      </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'basic_app:home' %}">Dashboard</a>
                        <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                    </div>
                </li>
            </ul>
            {% else %}
            <ul class="navbar-nav ml-auto">
                <!-- <li class="nav-item">
                    <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
                </li> -->

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'basic_app:register' %}" style="font-family: fo;">Register</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'basic_app:user_login' %}" style="font-family: fo;">Login</a>
                </li>
            </ul>
            {% endif%}
        </div>
    </nav>

    {% block body_block %} {% endblock %}

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</body>

</html>

qcc/templates/basic_app/frames.html
{% extends "basic_app/base.html" %} {% block body_block %}
<div class="container mt-4" style="min-height: 500px;">
    <div class="row">
        <div class="col-12 mx-auto">
            <nav aria-label="breadcrumb" style="font-size: 14px;">
                <ol class="breadcrumb bg-white">
                    <li class="breadcrumb-item"><a href="{% url 'basic_app:home' %}">Home</a></li>
                    <li class="breadcrumb-item" aria-current="page">
                        {% for s in subject %}
                        <a href="{% url 'basic_app:subject_detail' pk=s.id %}">
                         {{ s.subject_name }} 
                        </a> {% endfor %}
                    </li>
                    <li class="breadcrumb-item active" aria-current="page">
                        {% for t in topic %} {{ t.topic_name }} {% endfor %}
                    </li>
                </ol>
            </nav>
            <div class="">
                <ul class="nav nav-tabs" id="myTab" role="tablist">
                    {% for frame in frames_list %}
                    <li class="nav-item">
                        <a class="nav-link {% if forloop.first %}active{% endif %}" id="{{ frame.id }}-tab" data-toggle="tab" href="#f{{ frame.id }}" role="tab" aria-controls="{{ frame.id }}" aria-selected="true">{{ forloop.counter }}</a>
                    </li>
                    {% endfor %}
                    <li class="nav-item">
                        <a class="nav-link" id="test-tab" data-toggle="tab" href="#test_frame" role="tab" aria-controls="{{ frame.id }}" aria-selected="true">Test</a>
                    </li>
                </ul>
                <div class="tab-content" id="myTabContent">
                    {% for frame in frames_list %}
                    <div class="tab-pane {% if forloop.first %}active{% endif %} fade show p-2" id="f{{ frame.id }}" role="tabpanel" aria-labelledby="{{ frame.id }}-tab">

                        <div class="container">
                            <div class="row pt-4 pb-4">
                                <div class="col-md-5">
                                    <h5 style="font-weight: bold;">{{ frame }}</h5>
                                    <img src="{{ frame.img_url }}" alt="{{ frame.frame_name }}" style=' width: 100%; object-fit: contain; vertical-align: top;'>
                                </div>
                                <div class="col-md-7">
                                    {{ frame.frame_description | safe }}
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                    <div class="tab-pane fade show p-2" id="test_frame" role="tabpanel" aria-labelledby="test-tab">
                        <div class="container">
                            <div class="row pb-4">
                                <div class="col-12 text-center">
                                    {% if user_test %} {% for s in subject %} {% for t in topic %}
                                    <p style="font-family: acme; font-size: 20px; font-weight: lighter; margin-top: 30px;">You Have Already Taken the Test !</p>
                                    <a href="{% url 'basic_app:test' sid=s.id tid=t.id %}" class="btn btn-success mt-2">VIEW TEST RESULT</a> {% endfor %} {% endfor %} {%elif test%}
                                    <img src="https://www.larimer.org/sites/default/files/styles/media_responsive_widest/public/uploads/2018/new_well_done_inside_info_graphic.png?itok=u0XrlyX-" alt="{{ frame.frame_name }}" style=' width: 60%; height: 60%; object-fit: contain;'>
                                    <p style="font-family: acme; font-size: 20px; font-weight: lighter;">
                                        Congratulations on completing the Topic. Please Take a Test to check Your Memory.
                                    </p>
                                    {% for s in subject %} {% for t in topic %}
                                    <a href="{% url 'basic_app:test' sid=s.id tid=t.id %}" class="btn btn-success mt-2">TAKE TEST</a> {% endfor %} {% endfor %} {% else %}
                                    <p class="text-center" style="font-family: acme; font-size: 20px; font-weight: lighter;">No Active Tests for this Topic Now. Please Check Back Later !</p>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

qcc/templates/basic_app/index-orig.html
{% extends "basic_app/base.html" %} {% block body_block %}
<div class="row">
    <div class="col-md-6">
        <div class="">
            {% load static %}
            <img src="{% static 'basic_app/ol4.png' %}" alt="Online Learning" width="100%">
        </div>
    </div>
    <div class="col-md-6">
        <div class="">

        </div>
    </div>
</div>
{% endblock %}

qcc/templates/basic_app/registration.html
{% extends 'basic_app/base.html' %} {% load static %} {% block body_block %}

<div class="row">
    <div class="col-md-6 mx-auto mt-5">
        {% if registered %}
        <p class="mt-4" style="text-align: center; color: aliceblue;">Registered Successfully. <a href="{% url 'basic_app:user_login' %}">Click Here</a> to Login</p>
        {% else %}
        <div class="mt-4 shadow p-5 mb-5 bg-white rounded">

            <h3 style="text-align: center;">Registration</h3>
            {% if user_form.errors or profile_form.errors %}
            <div class="alert alert-danger mb-2" role="alert">
                {% for field in user_form %} {% for error in field.errors %}
                <strong>{{ error|escape }}</strong> {% endfor %} {% endfor %} {% for error in user_form.non_field_errors %}
                <strong>{{ error|escape }}</strong> {% endfor %} {% for field in profile_form %} {% for error in field.errors %}
                <strong>{{ error|escape }}</strong> {% endfor %} {% endfor %} {% for error in profile_form.non_field_errors %}
                <strong>{{ error|escape }}</strong> {% endfor %}
            </div>
            {% endif %}
            <form enctype="multipart/form-data" method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_username">Username</label>
                    <input type="text" class="form-control" name="username" maxlength="150" required id="id_username" aria-describedby="usernameHelp" placeholder="Enter Username">
                    <small id="usernameHelp" class="form-text text-muted">15 characters or fewer. Letters and digits only.</small>
                </div>
                <div class="form-group">
                    {{ user_form.email.errors }}
                    <label for="id_email">Email address</label>
                    <input type="email" class="form-control" name="email" maxlength="254" required id="id_email" aria-describedby="emailHelp" placeholder="Enter email">
                </div>
                <div class="form-group">
                    {{ user_form.password.errors }}
                    <label for="id_password">Password</label>
                    <input type="password" class="form-control" name="password" maxlength="128" required id="id_password" placeholder="Password">
                </div>
                <div class="form-group">
                    {{ profile_form.admission_number.errors }}
                    <label for="id_admission_number">Admission Number</label>
                    <input class="form-control" type="text" name="admission_number" maxlength="10" required id="id_admission_number" placeholder="Admission Number">
                </div>
                <div class="form-group">
                    {{ profile_form.address.errors }}
                    <label for="id_address">Address</label>
                    <input type="text" class="form-control" name="address" maxlength="256" required id="id_address" placeholder="Address">
                </div>
                <div class="form-group">
                    {{ profile_form.contact.errors }}
                    <label for="id_contact">Contact Number</label>
                    <input type="text" class="form-control" name="contact" maxlength="10" required id="id_contact" placeholder="Contact Number">
                </div>
                <div class="form-group mb-0 mt-4">
                    <input type="submit" value="Register" class="btn btn-block btn-primary">
                </div>
            </form>
            <!-- <form enctype="multipart/form-data" method="POST">
                <input type="hidden" name="csrfmiddlewaretoken" value="mUnjryXof5L7xn3Dlx34TGgs1TOH7DNS4evTtMH2fXjqGVIRPpwgUtKeUjhyOODk">
                <p><label for="id_username">Username:</label> <input type="text" name="username" maxlength="150" required id="id_username"> <span class="helptext">Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.</span></p>
                <p><label for="id_email">Email address:</label> <input type="email" name="email" maxlength="254" id="id_email"></p>
                <p><label for="id_password">Password:</label> <input type="text" name="password" maxlength="128" required id="id_password"></p>
                <p><label for="id_admission_number">Admission number:</label> <input type="text" name="admission_number" maxlength="10" required id="id_admission_number"></p>
                <p><label for="id_address">Address:</label> <input type="text" name="address" maxlength="256" required id="id_address"></p>
                <p><label for="id_contact">Contact:</label> <input type="text" name="contact" maxlength="10" required id="id_contact"></p>
                <input type="submit" value="Register" class="btn btn-primary">
            </form> -->

        </div>
        {% endif %}
    </div>
</div>

{% endblock %}